// data-kps.js —— 小学数学全部知识点清单（底稿）
// 字段：id / g(年级1-6) / domain(领域) / name(知识点名) / tip(一句话讲解，用于「提示」与诊断后的反向教学)
// domain: number=数与运算 · geo=图形几何 · measure=量与计量 · stat=统计与概率 · think=综合实践
const KPS = [
  // ————— 一年级（17） —————
  { id: "g1_count", g: 1, domain: "number", name: "数一数·基数与序数", tip: "数出总数是基数（一共几个），排第几是序数（第几个），两者不要混。" },
  { id: "g1_compare", g: 1, domain: "number", name: "比多少", tip: "一一对应比较：谁多、谁少、同样多；求「长几/多几」用减法。" },
  { id: "g1_pos", g: 1, domain: "geo", name: "位置（上下前后左右）", tip: "位置是相对的：A 在 B 的上面，B 就在 A 的下面，说方向要先定参照物。" },
  { id: "g1_add5", g: 1, domain: "number", name: "1~5 的认识与加减", tip: "1~5 能分成几和几（数的组成），加法是合起来，减法是拿走。" },
  { id: "g1_solid", g: 1, domain: "geo", name: "认识图形（一）·立体图形", tip: "长方体、正方体、圆柱、球的特征：正方体六个面都是正方形，球滚动不分方向。" },
  { id: "g1_add10", g: 1, domain: "number", name: "6~10 的认识与加减", tip: "10 的组成是凑十法的基础：看到 9 想 1、看到 8 想 2。" },
  { id: "g1_teen", g: 1, domain: "number", name: "11~20 各数的认识", tip: "十几 = 1 个十和几个一；顺序是 11、12…20，会倒着数。" },
  { id: "g1_add20", g: 1, domain: "number", name: "20 以内进位加法", tip: "凑十法：先凑成 10 再加剩下的，如 8+5 = 8+2+3 = 13。" },
  { id: "g1_clock", g: 1, domain: "measure", name: "认识钟表", tip: "短针是时、长针是分；分针指 12 是整时，指 6 是半时；推算时刻用加减。" },
  { id: "g1_class", g: 1, domain: "think", name: "分类与整理", tip: "先定分类标准（颜色/形状/用途），标准不同结果不同，分完数一数填表。" },
  { id: "g1_plane", g: 1, domain: "geo", name: "认识图形（二）·平面图形", tip: "长方形对边相等、正方形四边相等、三角形三条边、圆是弯弯的封闭曲线。" },
  { id: "g1_num100", g: 1, domain: "number", name: "100 以内数的认识", tip: "从右边起：个位、十位、百位；十位是几就表示几个十。" },
  { id: "g1_add100a", g: 1, domain: "number", name: "100 以内加减法（一）", tip: "整十数加减：几十加几十直接十位相加；也要会估一估大约是多少。" },
  { id: "g1_money", g: 1, domain: "measure", name: "认识人民币", tip: "1 元 = 10 角 = 100 分；算钱把相同单位的先加起来，再换算单位。" },
  { id: "g1_add100b", g: 1, domain: "number", name: "100 以内加减法（二）", tip: "笔算对齐个位，个位满十向十位进 1，个位不够减向十位借 1 当 10。" },
  { id: "g1_pattern", g: 1, domain: "think", name: "找规律", tip: "先看重复的「一组」是什么，或每次多几/少几，再往后推。" },
  { id: "g1_stat1", g: 1, domain: "stat", name: "统计（分类计数）", tip: "数图形/物品时按种类分别数，数完可比多少、求一共。" },

  // ————— 二年级（13） —————
  { id: "g2_length", g: 2, domain: "measure", name: "长度单位（厘米、米）", tip: "1 米 = 100 厘米；较短用厘米、较长用米；几段合起来用乘或连加。" },
  { id: "g2_add100", g: 2, domain: "number", name: "100 以内加减法（笔算与估算）", tip: "笔算数位对齐；估算把数看成整十整百再算，用来判断大约多少。" },
  { id: "g2_angle", g: 2, domain: "geo", name: "角的初步认识", tip: "角有一个顶点两条边；直角=三角尺的角，比直角小是锐角，大是钝角。" },
  { id: "g2_mul", g: 2, domain: "number", name: "表内乘法（乘法口诀）", tip: "乘法是求几个相同加数的和；口诀要背熟，看到 3×7 立刻想三七二十一。" },
  { id: "g2_observe", g: 2, domain: "geo", name: "观察物体", tip: "从前面、侧面、上面看同一物体形状可能不同；站在不同方向看到的不一样。" },
  { id: "g2_div", g: 2, domain: "number", name: "表内除法", tip: "除法是平均分：每份几个用除；想乘法算除法，口诀反过来用。" },
  { id: "g2_mixed", g: 2, domain: "number", name: "混合运算", tip: "先乘除后加减；有括号先算括号里面的。" },
  { id: "g2_remainder", g: 2, domain: "number", name: "有余数的除法", tip: "被除数 = 除数×商 + 余数；余数一定比除数小。" },
  { id: "g2_wan", g: 2, domain: "number", name: "万以内数的认识", tip: "数位顺序：个十百千万；读数从高位起，中间的 0 要读、末尾的 0 不读。" },
  { id: "g2_mass", g: 2, domain: "measure", name: "克和千克", tip: "1 千克 = 1000 克；较轻用克、较重用千克；换算大单位乘、小单位除。" },
  { id: "g2_addsub_wan", g: 2, domain: "number", name: "万以内加减法（一）", tip: "口算整百整十加减；估算时把数看作接近的整百整千再算。" },
  { id: "g2_stat2", g: 2, domain: "stat", name: "数据收集整理", tip: "用画正字等方法记录数据，填进统计表，再求总数与差。" },
  { id: "g2_combo", g: 2, domain: "think", name: "数学广角·推理与搭配", tip: "搭配要有序地列：先定一件再配另一件，做到不重复不遗漏。" },

  // ————— 三年级（19） —————
  { id: "g3_time", g: 3, domain: "measure", name: "时、分、秒", tip: "1 时 = 60 分、1 分 = 60 秒；算经过时间：结束时刻 − 开始时刻。" },
  { id: "g3_addsub", g: 3, domain: "number", name: "万以内加减法（二）", tip: "笔算从个位算起，连续进位/退位别丢；算完可估算验一下。" },
  { id: "g3_measure", g: 3, domain: "measure", name: "测量（毫米分米、千米、吨）", tip: "1 千米 = 1000 米，1 米 = 10 分米 = 100 厘米，1 吨 = 1000 千克。" },
  { id: "g3_mul3", g: 3, domain: "number", name: "多位数乘一位数", tip: "从个位乘起，哪一位乘得满几十就向前一位进几。" },
  { id: "g3_times", g: 3, domain: "number", name: "倍的认识", tip: "谁是谁的几倍用除法；求一个数的几倍用乘法。" },
  { id: "g3_frac1", g: 3, domain: "number", name: "分数的初步认识", tip: "把一个整体平均分成几份，取几份就是几分之几——必须先「平均分」。" },
  { id: "g3_peri", g: 3, domain: "geo", name: "长方形和正方形·周长", tip: "长方形周长 =（长+宽）×2；正方形周长 = 边长×4；周长是一圈的长度。" },
  { id: "g3_div3", g: 3, domain: "number", name: "多位数除以一位数", tip: "从最高位除起，除到哪一位商就写在哪一位，别忘验算：商×除数+余数。" },
  { id: "g3_div3b", g: 3, domain: "number", name: "除数是一位数的除法（验算）", tip: "验算：没有余数用商×除数=被除数；有余数再加上余数。" },
  { id: "g3_set", g: 3, domain: "think", name: "数学广角·集合", tip: "两组有重叠时：总数 = A + B − 重叠部分（重叠的只算一次）。" },
  { id: "g3_bar1", g: 3, domain: "stat", name: "条形统计图（一格代表一）", tip: "条形图直接看高低比多少；一格代表 1 时数格子就是数量。" },
  { id: "g3_dir", g: 3, domain: "geo", name: "位置与方向", tip: "面北而立：左西右东、背后是南；先定基准方向再判断。" },
  { id: "g3_2stat", g: 3, domain: "stat", name: "复式统计表", tip: "把两组（如男/女）数据合在一张表里，便于同时比较两组。" },
  { id: "g3_2x2", g: 3, domain: "number", name: "两位数乘两位数", tip: "先用第二个因数个位乘，再用十位乘（错一位），最后相加。" },
  { id: "g3_area", g: 3, domain: "geo", name: "面积与面积单位", tip: "面积是面的大小：1 平方分米 = 100 平方厘米，1 平方米 = 100 平方分米。" },
  { id: "g3_areaRect", g: 3, domain: "geo", name: "长方形和正方形的面积", tip: "长方形面积 = 长×宽；正方形面积 = 边长×边长——面积和周长别混。" },
  { id: "g3_date", g: 3, domain: "measure", name: "年、月、日与 24 时计时法", tip: "大月 31 天（1/3/5/7/8/10/12 月），小月 30 天；平年 2 月 28 天、闰年 29 天。" },
  { id: "g3_dec1", g: 3, domain: "number", name: "小数的初步认识", tip: "几元几角写成小数：5 角 = 0.5 元；小数点左边是整数、右边十分位。" },
  { id: "g3_combo2", g: 3, domain: "think", name: "数学广角·搭配（二）", tip: "组数/排队问题按顺序枚举：先定十位再定个位，不重不漏。" },

  // ————— 四年级（16） —————
  { id: "g4_big", g: 4, domain: "number", name: "大数的认识（改写与四舍五入）", tip: "改写用「万/亿」作单位；四舍五入看尾数首位：满 5 进 1，不足 5 舍去。" },
  { id: "g4_code", g: 4, domain: "think", name: "数字编码", tip: "编码每个位置有含义（如楼号-层号-序号），按规则逐段解读。" },
  { id: "g4_land", g: 4, domain: "measure", name: "公顷和平方千米", tip: "1 公顷 = 10000 平方米（边长 100 米的正方形），1 平方千米 = 100 公顷。" },
  { id: "g4_angle4", g: 4, domain: "geo", name: "角的度量", tip: "量角器中心对顶点、0 刻度线对一边；余角 = 90° − 已知角，补角 = 180° − 已知角。" },
  { id: "g4_mul4", g: 4, domain: "number", name: "三位数乘两位数", tip: "先乘个位再乘十位，第二部分错开一位相加。" },
  { id: "g4_para", g: 4, domain: "geo", name: "平行四边形和梯形", tip: "平行四边形两组对边分别平行；梯形只有一组对边平行；平行四边形易变形。" },
  { id: "g4_div4", g: 4, domain: "number", name: "除数是两位数的除法", tip: "把除数看作整十数试商，初商大了调小、小了调大；记得验算。" },
  { id: "g4_bar2", g: 4, domain: "stat", name: "条形统计图（一格代表多）", tip: "一格代表几先看清，数量 = 格数 × 每格代表的数。" },
  { id: "g4_opt", g: 4, domain: "think", name: "数学广角·优化", tip: "沏茶、烙饼类问题：能同时做的事同时做，锅要尽量放满，步骤最少时间最短。" },
  { id: "g4_law", g: 4, domain: "number", name: "运算定律（简便计算）", tip: "加法交换/结合、乘法交换/结合/分配；看到 25×4、125×8 先凑整。" },
  { id: "g4_dec", g: 4, domain: "number", name: "小数的意义和性质", tip: "小数点右边依次是十分位、百分位；小数末尾的 0 可去掉但大小不变。" },
  { id: "g4_decadd", g: 4, domain: "number", name: "小数的加减法", tip: "小数点对齐再算；得数末尾有 0 通常要化简。" },
  { id: "g4_tri", g: 4, domain: "geo", name: "三角形", tip: "三角形任意两边之和大于第三边；三个内角和 = 180°。" },
  { id: "g4_sym", g: 4, domain: "geo", name: "图形的运动（二）·轴对称与平移", tip: "对称图形沿对称轴对折完全重合；平移只挪位置不转方向。" },
  { id: "g4_avg", g: 4, domain: "stat", name: "平均数", tip: "平均数 = 总数 ÷ 个数；它在最大和最小之间，代表整体水平。" },
  { id: "g4_cfr", g: 4, domain: "think", name: "数学广角·鸡兔同笼", tip: "假设全是鸡：脚差 ÷ 2 = 兔的只数；或用方程设 x 解。" },

  // ————— 五年级（14） —————
  { id: "g5_muldec", g: 5, domain: "number", name: "小数乘法", tip: "先按整数乘，再数因数里共有几位小数，从积的右边点上小数点。" },
  { id: "g5_divdec", g: 5, domain: "number", name: "小数除法", tip: "除数是小数先移动小数点变成整数，被除数同时移动；除不尽按要求取近似数。" },
  { id: "g5_prob", g: 5, domain: "stat", name: "可能性", tip: "可能性大小 = 符合条件的个数 ÷ 总个数；数量越多可能性越大。" },
  { id: "g5_eq", g: 5, domain: "number", name: "简易方程", tip: "先找等量关系再设未知数；解方程利用等式性质，两边同时加减乘除同一个数。" },
  { id: "g5_multiArea", g: 5, domain: "geo", name: "多边形的面积", tip: "平行四边形=底×高；三角形=底×高÷2；梯形=（上底+下底）×高÷2。" },
  { id: "g5_factor", g: 5, domain: "number", name: "因数与倍数", tip: "a÷b=c（整除）则 a 是 b 的倍数、b 是 a 的因数；一个数的因数成对出现。" },
  { id: "g5_prime", g: 5, domain: "number", name: "质数与合数", tip: "质数只有 1 和它本身两个因数（2 是唯一的偶质数）；1 既不是质数也不是合数。" },
  { id: "g5_gcd", g: 5, domain: "number", name: "最大公因数与最小公倍数", tip: "找公因数短除法；约分用最大公因数，通分用最小公倍数。" },
  { id: "g5_fracprop", g: 5, domain: "number", name: "分数的意义和性质", tip: "分数基本性质：分子分母同乘/除以相同的数（0 除外）大小不变；约分到最简。" },
  { id: "g5_rot", g: 5, domain: "geo", name: "图形的运动（三）·旋转", tip: "旋转要定中心、方向、角度；钟面一小时 = 30°。" },
  { id: "g5_fracadd", g: 5, domain: "number", name: "分数的加减法", tip: "同分母直接加减分子；异分母先通分再算，结果能约分要约分。" },
  { id: "g5_vol", g: 5, domain: "geo", name: "长方体和正方体（体积容积）", tip: "长方体体积 = 长×宽×高；体积单位：1 立方米 = 1000 立方分米。" },
  { id: "g5_line", g: 5, domain: "stat", name: "折线统计图", tip: "折线图看点与线，擅长反映数量的增减变化趋势。" },
  { id: "g5_plant", g: 5, domain: "think", name: "数学广角·植树问题", tip: "两端都栽：棵数 = 间隔数 + 1；两端都不栽：棵数 = 间隔数 − 1。" },
  { id: "g5_find", g: 5, domain: "think", name: "数学广角·找次品", tip: "尽量分成 3 份用天平称，次数最少；8 个零件 1 个偏轻，2 次保证找到。" },

  // ————— 六年级（12） —————
  { id: "g6_fracmul", g: 6, domain: "number", name: "分数乘法", tip: "分子乘分子、分母乘分母，能约先约；求一个数的几分之几用乘法。" },
  { id: "g6_fracdiv", g: 6, domain: "number", name: "分数除法", tip: "除以一个数 = 乘这个数的倒数；已知部分求整体常用除法。" },
  { id: "g6_pct", g: 6, domain: "number", name: "百分数（意义与互化）", tip: "百分数表示占比：25% = 25/100 = 0.25；百分数不带单位。" },
  { id: "g6_pctapp", g: 6, domain: "number", name: "百分数（二）·折扣与税率", tip: "打八折 = 原价 × 80%；求便宜了多少用原价 − 折后价。" },
  { id: "g6_ratio", g: 6, domain: "number", name: "比的意义和基本性质", tip: "比的前项÷后项 = 比值；按比分配：先算每份，再乘各份数。" },
  { id: "g6_prop", g: 6, domain: "number", name: "比例（解比例、正反比例）", tip: "比例两内项积 = 两外项积；比值一定成正比例，乘积一定成反比例。" },
  { id: "g6_scale", g: 6, domain: "geo", name: "比例尺与图形的放大缩小", tip: "比例尺 = 图上距离 : 实际距离；1:1000 即图上 1 厘米代表实际 10 米。" },
  { id: "g6_circle", g: 6, domain: "geo", name: "圆（周长与面积）", tip: "C = πd = 2πr，S = πr²；π 取 3.14，直径 = 半径 × 2。" },
  { id: "g6_fan", g: 6, domain: "stat", name: "扇形统计图", tip: "扇形占整圆的百分比 = 圆心角 ÷ 360°；圆心角 = 360° × 百分比。" },
  { id: "g6_neg", g: 6, domain: "number", name: "负数的初步认识", tip: "0 不是正数也不是负数；求两个数相差多少（跨 0）把它们的差加起来。" },
  { id: "g6_cyl", g: 6, domain: "geo", name: "圆柱与圆锥", tip: "圆柱体积 = 底面积×高；等底等高的圆锥体积是圆柱的 1/3。" },
  { id: "g6_np", g: 6, domain: "think", name: "数学广角·数与形", tip: "数能画成形、形能读成数；从 1=1²、1+3=2² 发现连续奇数和的规律。" },
];

if (typeof module !== "undefined") module.exports = { KPS };
